// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkyWBtUXKqjVNP8bZaDTMRtiqmqtfeGZQ',
    appId: '1:235687709046:web:84e357acb98573186f5257',
    messagingSenderId: '235687709046',
    projectId: 'ship-tracker-firebase',
    authDomain: 'ship-tracker-firebase.firebaseapp.com',
    storageBucket: 'ship-tracker-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYa_q6l5imQ3QRSJcfceDA5N4sdNZO0o',
    appId: '1:235687709046:android:9ac2ee7c3f05e5666f5257',
    messagingSenderId: '235687709046',
    projectId: 'ship-tracker-firebase',
    storageBucket: 'ship-tracker-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lsmVqaWGSyE6cJAmpJocodbPcbKsDRU',
    appId: '1:235687709046:ios:0d43f280fd122f756f5257',
    messagingSenderId: '235687709046',
    projectId: 'ship-tracker-firebase',
    storageBucket: 'ship-tracker-firebase.appspot.com',
    iosBundleId: 'com.example.shipTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2lsmVqaWGSyE6cJAmpJocodbPcbKsDRU',
    appId: '1:235687709046:ios:0d43f280fd122f756f5257',
    messagingSenderId: '235687709046',
    projectId: 'ship-tracker-firebase',
    storageBucket: 'ship-tracker-firebase.appspot.com',
    iosBundleId: 'com.example.shipTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkyWBtUXKqjVNP8bZaDTMRtiqmqtfeGZQ',
    appId: '1:235687709046:web:99b5bd84df74bd566f5257',
    messagingSenderId: '235687709046',
    projectId: 'ship-tracker-firebase',
    authDomain: 'ship-tracker-firebase.firebaseapp.com',
    storageBucket: 'ship-tracker-firebase.appspot.com',
  );
}
